name: bweather
description: A Beautiful Weather App
version: 1.0.0+1
publish_to: none

environment:
    sdk: ">=2.14.0 <3.0.0"

dependencies:
    bloc: ^8.0.1
    flutter:
        sdk: flutter
    flutter_bloc: ^8.0.0
    flutter_hooks: ^0.18.1
    flutter_localizations:
        sdk: flutter
    freezed_annotation: ^1.1.0
    geolocator: ^8.0.1
    get_it: ^7.2.0
    google_fonts: ^2.1.1
    injectable: ^1.5.0
    intl: ^0.17.0
    json_serializable: ^6.1.3
    shared_preferences: ^2.0.11

dev_dependencies:
    bloc_test: ^9.0.1
    build_runner: ^2.1.7
    flutter_test:
        sdk: flutter
    freezed: ^1.0.0
    injectable_generator: ^1.5.2
    mocktail: ^0.2.0
    very_good_analysis: ^2.4.0

flutter:
    uses-material-design: true
    generate: true
