name: dio_provider
description: A reusable and injectable Dio di module.
version: 0.0.1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies: 
  dio: ^4.0.6
  get_it: ^7.2.0
  injectable: ^2.1.0

dev_dependencies:
  build_runner: ^2.3.3
  injectable_generator: ^2.1.3
  lint: ^2.0.1
  mockito: ^5.3.2
  test: ^1.16.0
