name: logger_wrapper
description: A flexible and fully configurable ready to use wrapper around Logger package.
version: 0.0.1
# homepage: https://www.example.com

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies: 
  get_it: ^7.2.0
  injectable: ^2.1.0
  logging: ^1.1.0

dev_dependencies:
  build_runner: ^2.3.3
  injectable_generator: ^2.1.3
  lint: ^2.0.1
  test: ^1.16.0
