name: weather_api
description: Domain layer for weather used in Bweather application
version: 0.0.1
publish_to: none

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies: 
  dio_provider:
    path: ../dio_provider/

  envied: ^0.3.0

  weather_repository:
    path: ./packages/weather_repository/

dev_dependencies:
  build_runner: ^2.3.3
  envied_generator: ^0.3.0
  lint: ^2.0.1
  mockito: ^5.3.2
  test: ^1.16.0
