name: openweather_repository
description: Weather data layer & repository for Bweather application
version: 0.0.1
publish_to: none

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  dio_provider:
    path: ../dio_provider/

  envied: ^0.3.0
  freezed_annotation: ^2.2.0
  json_annotation: ^4.7.0

dev_dependencies:
  build_runner: ^2.3.3
  envied_generator: ^0.3.0
  freezed: ^2.3.2
  json_serializable: ^6.5.4
  lint: ^2.0.1
  test: ^1.16.0
