import 'package:test/test.dart';
import 'package:weather_repository/src/models/weather.dart';

void main() {
  final response = {
    "location": {
      "name": "London",
      "region": "City of London, Greater London",
      "country": "United Kingdom",
      "lat": 51.52,
      "lon": -0.11,
      "tz_id": "Europe/London",
      "localtime_epoch": 1671513665,
      "localtime": "2022-12-20 5:21"
    },
    "current": {
      "last_updated_epoch": 1671513300,
      "last_updated": "2022-12-20 05:15",
      "temp_c": 13.0,
      "temp_f": 55.4,
      "is_day": 0,
      "condition": {
        "text": "Light rain",
        "icon": "//cdn.weatherapi.com/weather/64x64/night/296.png",
        "code": 1183
      },
      "wind_mph": 16.1,
      "wind_kph": 25.9,
      "wind_degree": 200,
      "wind_dir": "SSW",
      "pressure_mb": 1004.0,
      "pressure_in": 29.65,
      "precip_mm": 0.5,
      "precip_in": 0.02,
      "humidity": 88,
      "cloud": 100,
      "feelslike_c": 10.6,
      "feelslike_f": 51.0,
      "vis_km": 6.0,
      "vis_miles": 3.0,
      "uv": 1.0,
      "gust_mph": 26.6,
      "gust_kph": 42.8,
      "air_quality": {
        "co": 213.60000610351562,
        "no2": 8.899999618530273,
        "o3": 43.599998474121094,
        "so2": 5.099999904632568,
        "pm2_5": 2.0,
        "pm10": 2.4000000953674316,
        "us-epa-index": 1,
        "gb-defra-index": 1
      }
    },
    "forecast": {
      "forecastday": [
        {
          "date": "2022-12-20",
          "date_epoch": 1671494400,
          "day": {
            "maxtemp_c": 12.3,
            "maxtemp_f": 54.1,
            "mintemp_c": 6.5,
            "mintemp_f": 43.7,
            "avgtemp_c": 10.4,
            "avgtemp_f": 50.8,
            "maxwind_mph": 18.1,
            "maxwind_kph": 29.2,
            "totalprecip_mm": 10.5,
            "totalprecip_in": 0.41,
            "totalsnow_cm": 0.0,
            "avgvis_km": 8.2,
            "avgvis_miles": 5.0,
            "avghumidity": 84.0,
            "daily_will_it_rain": 1,
            "daily_chance_of_rain": 98,
            "daily_will_it_snow": 0,
            "daily_chance_of_snow": 0,
            "condition": {
              "text": "Moderate rain",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/302.png",
              "code": 1189
            },
            "uv": 3.0
          },
          "astro": {
            "sunrise": "08:03 AM",
            "sunset": "03:53 PM",
            "moonrise": "04:18 AM",
            "moonset": "01:33 PM",
            "moon_phase": "Waning Crescent",
            "moon_illumination": "11"
          },
          "hour": [
            {
              "time_epoch": 1671494400,
              "time": "2022-12-20 00:00",
              "temp_c": 12.8,
              "temp_f": 55.0,
              "is_day": 0,
              "condition": {
                "text": "Moderate rain",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/302.png",
                "code": 1189
              },
              "wind_mph": 17.0,
              "wind_kph": 27.4,
              "wind_degree": 207,
              "wind_dir": "SSW",
              "pressure_mb": 1005.0,
              "pressure_in": 29.68,
              "precip_mm": 3.4,
              "precip_in": 0.13,
              "humidity": 91,
              "cloud": 100,
              "feelslike_c": 10.4,
              "feelslike_f": 50.7,
              "windchill_c": 10.4,
              "windchill_f": 50.7,
              "heatindex_c": 12.8,
              "heatindex_f": 55.0,
              "dewpoint_c": 11.3,
              "dewpoint_f": 52.3,
              "will_it_rain": 1,
              "chance_of_rain": 98,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 7.0,
              "vis_miles": 4.0,
              "gust_mph": 26.2,
              "gust_kph": 42.1,
              "uv": 1.0
            },
            {
              "time_epoch": 1671498000,
              "time": "2022-12-20 01:00",
              "temp_c": 12.6,
              "temp_f": 54.7,
              "is_day": 0,
              "condition": {
                "text": "Light drizzle",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/266.png",
                "code": 1153
              },
              "wind_mph": 14.8,
              "wind_kph": 23.8,
              "wind_degree": 204,
              "wind_dir": "SSW",
              "pressure_mb": 1005.0,
              "pressure_in": 29.66,
              "precip_mm": 0.5,
              "precip_in": 0.02,
              "humidity": 93,
              "cloud": 100,
              "feelslike_c": 10.4,
              "feelslike_f": 50.7,
              "windchill_c": 10.4,
              "windchill_f": 50.7,
              "heatindex_c": 12.6,
              "heatindex_f": 54.7,
              "dewpoint_c": 11.4,
              "dewpoint_f": 52.5,
              "will_it_rain": 1,
              "chance_of_rain": 98,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 2.0,
              "vis_miles": 1.0,
              "gust_mph": 22.8,
              "gust_kph": 36.7,
              "uv": 1.0
            },
            {
              "time_epoch": 1671501600,
              "time": "2022-12-20 02:00",
              "temp_c": 12.6,
              "temp_f": 54.7,
              "is_day": 0,
              "condition": {
                "text": "Light rain",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/296.png",
                "code": 1183
              },
              "wind_mph": 18.1,
              "wind_kph": 29.2,
              "wind_degree": 205,
              "wind_dir": "SSW",
              "pressure_mb": 1004.0,
              "pressure_in": 29.66,
              "precip_mm": 0.9,
              "precip_in": 0.04,
              "humidity": 91,
              "cloud": 100,
              "feelslike_c": 10.0,
              "feelslike_f": 50.0,
              "windchill_c": 10.0,
              "windchill_f": 50.0,
              "heatindex_c": 12.6,
              "heatindex_f": 54.7,
              "dewpoint_c": 11.2,
              "dewpoint_f": 52.2,
              "will_it_rain": 1,
              "chance_of_rain": 76,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 9.0,
              "vis_miles": 5.0,
              "gust_mph": 26.8,
              "gust_kph": 43.2,
              "uv": 1.0
            },
            {
              "time_epoch": 1671505200,
              "time": "2022-12-20 03:00",
              "temp_c": 12.4,
              "temp_f": 54.3,
              "is_day": 0,
              "condition": {
                "text": "Light rain",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/296.png",
                "code": 1183
              },
              "wind_mph": 16.6,
              "wind_kph": 26.6,
              "wind_degree": 204,
              "wind_dir": "SSW",
              "pressure_mb": 1004.0,
              "pressure_in": 29.66,
              "precip_mm": 2.2,
              "precip_in": 0.09,
              "humidity": 90,
              "cloud": 100,
              "feelslike_c": 9.9,
              "feelslike_f": 49.8,
              "windchill_c": 9.9,
              "windchill_f": 49.8,
              "heatindex_c": 12.4,
              "heatindex_f": 54.3,
              "dewpoint_c": 10.8,
              "dewpoint_f": 51.4,
              "will_it_rain": 1,
              "chance_of_rain": 75,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 9.0,
              "vis_miles": 5.0,
              "gust_mph": 25.1,
              "gust_kph": 40.3,
              "uv": 1.0
            },
            {
              "time_epoch": 1671508800,
              "time": "2022-12-20 04:00",
              "temp_c": 12.7,
              "temp_f": 54.9,
              "is_day": 0,
              "condition": {
                "text": "Light drizzle",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/266.png",
                "code": 1153
              },
              "wind_mph": 17.4,
              "wind_kph": 28.1,
              "wind_degree": 199,
              "wind_dir": "SSW",
              "pressure_mb": 1004.0,
              "pressure_in": 29.65,
              "precip_mm": 0.4,
              "precip_in": 0.02,
              "humidity": 88,
              "cloud": 100,
              "feelslike_c": 10.2,
              "feelslike_f": 50.4,
              "windchill_c": 10.2,
              "windchill_f": 50.4,
              "heatindex_c": 12.7,
              "heatindex_f": 54.9,
              "dewpoint_c": 10.8,
              "dewpoint_f": 51.4,
              "will_it_rain": 1,
              "chance_of_rain": 86,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 2.0,
              "vis_miles": 1.0,
              "gust_mph": 26.6,
              "gust_kph": 42.8,
              "uv": 1.0
            },
            {
              "time_epoch": 1671512400,
              "time": "2022-12-20 05:00",
              "temp_c": 12.5,
              "temp_f": 54.5,
              "is_day": 0,
              "condition": {
                "text": "Light drizzle",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/266.png",
                "code": 1153
              },
              "wind_mph": 17.7,
              "wind_kph": 28.4,
              "wind_degree": 199,
              "wind_dir": "SSW",
              "pressure_mb": 1004.0,
              "pressure_in": 29.64,
              "precip_mm": 0.5,
              "precip_in": 0.02,
              "humidity": 89,
              "cloud": 100,
              "feelslike_c": 9.9,
              "feelslike_f": 49.8,
              "windchill_c": 9.9,
              "windchill_f": 49.8,
              "heatindex_c": 12.5,
              "heatindex_f": 54.5,
              "dewpoint_c": 10.7,
              "dewpoint_f": 51.3,
              "will_it_rain": 0,
              "chance_of_rain": 61,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 2.0,
              "vis_miles": 1.0,
              "gust_mph": 26.6,
              "gust_kph": 42.8,
              "uv": 1.0
            },
            {
              "time_epoch": 1671516000,
              "time": "2022-12-20 06:00",
              "temp_c": 12.3,
              "temp_f": 54.1,
              "is_day": 0,
              "condition": {
                "text": "Light rain",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/296.png",
                "code": 1183
              },
              "wind_mph": 15.2,
              "wind_kph": 24.5,
              "wind_degree": 209,
              "wind_dir": "SSW",
              "pressure_mb": 1004.0,
              "pressure_in": 29.64,
              "precip_mm": 1.9,
              "precip_in": 0.07,
              "humidity": 92,
              "cloud": 100,
              "feelslike_c": 9.9,
              "feelslike_f": 49.8,
              "windchill_c": 9.9,
              "windchill_f": 49.8,
              "heatindex_c": 12.3,
              "heatindex_f": 54.1,
              "dewpoint_c": 10.9,
              "dewpoint_f": 51.6,
              "will_it_rain": 1,
              "chance_of_rain": 96,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 9.0,
              "vis_miles": 5.0,
              "gust_mph": 23.0,
              "gust_kph": 37.1,
              "uv": 1.0
            },
            {
              "time_epoch": 1671519600,
              "time": "2022-12-20 07:00",
              "temp_c": 11.8,
              "temp_f": 53.2,
              "is_day": 0,
              "condition": {
                "text": "Light drizzle",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/266.png",
                "code": 1153
              },
              "wind_mph": 8.7,
              "wind_kph": 14.0,
              "wind_degree": 245,
              "wind_dir": "WSW",
              "pressure_mb": 1004.0,
              "pressure_in": 29.65,
              "precip_mm": 0.3,
              "precip_in": 0.01,
              "humidity": 92,
              "cloud": 100,
              "feelslike_c": 10.2,
              "feelslike_f": 50.4,
              "windchill_c": 10.2,
              "windchill_f": 50.4,
              "heatindex_c": 11.8,
              "heatindex_f": 53.2,
              "dewpoint_c": 10.5,
              "dewpoint_f": 50.9,
              "will_it_rain": 1,
              "chance_of_rain": 96,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 2.0,
              "vis_miles": 1.0,
              "gust_mph": 13.2,
              "gust_kph": 21.2,
              "uv": 1.0
            },
            {
              "time_epoch": 1671523200,
              "time": "2022-12-20 08:00",
              "temp_c": 10.8,
              "temp_f": 51.4,
              "is_day": 0,
              "condition": {
                "text": "Overcast",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/122.png",
                "code": 1009
              },
              "wind_mph": 6.7,
              "wind_kph": 10.8,
              "wind_degree": 293,
              "wind_dir": "WNW",
              "pressure_mb": 1006.0,
              "pressure_in": 29.69,
              "precip_mm": 0.0,
              "precip_in": 0.0,
              "humidity": 85,
              "cloud": 100,
              "feelslike_c": 9.5,
              "feelslike_f": 49.1,
              "windchill_c": 9.5,
              "windchill_f": 49.1,
              "heatindex_c": 10.8,
              "heatindex_f": 51.4,
              "dewpoint_c": 8.4,
              "dewpoint_f": 47.1,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10.0,
              "vis_miles": 6.0,
              "gust_mph": 9.8,
              "gust_kph": 15.8,
              "uv": 1.0
            },
            {
              "time_epoch": 1671526800,
              "time": "2022-12-20 09:00",
              "temp_c": 10.5,
              "temp_f": 50.9,
              "is_day": 1,
              "condition": {
                "text": "Patchy light drizzle",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/263.png",
                "code": 1150
              },
              "wind_mph": 10.1,
              "wind_kph": 16.2,
              "wind_degree": 265,
              "wind_dir": "W",
              "pressure_mb": 1007.0,
              "pressure_in": 29.72,
              "precip_mm": 0.3,
              "precip_in": 0.01,
              "humidity": 80,
              "cloud": 71,
              "feelslike_c": 8.4,
              "feelslike_f": 47.1,
              "windchill_c": 8.4,
              "windchill_f": 47.1,
              "heatindex_c": 10.5,
              "heatindex_f": 50.9,
              "dewpoint_c": 7.3,
              "dewpoint_f": 45.1,
              "will_it_rain": 0,
              "chance_of_rain": 63,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 5.0,
              "vis_miles": 3.0,
              "gust_mph": 14.5,
              "gust_kph": 23.4,
              "uv": 3.0
            },
            {
              "time_epoch": 1671530400,
              "time": "2022-12-20 10:00",
              "temp_c": 10.2,
              "temp_f": 50.4,
              "is_day": 1,
              "condition": {
                "text": "Sunny",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                "code": 1000
              },
              "wind_mph": 8.5,
              "wind_kph": 13.7,
              "wind_degree": 252,
              "wind_dir": "WSW",
              "pressure_mb": 1007.0,
              "pressure_in": 29.75,
              "precip_mm": 0.0,
              "precip_in": 0.0,
              "humidity": 79,
              "cloud": 3,
              "feelslike_c": 8.3,
              "feelslike_f": 46.9,
              "windchill_c": 8.3,
              "windchill_f": 46.9,
              "heatindex_c": 10.2,
              "heatindex_f": 50.4,
              "dewpoint_c": 6.8,
              "dewpoint_f": 44.2,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10.0,
              "vis_miles": 6.0,
              "gust_mph": 11.9,
              "gust_kph": 19.1,
              "uv": 4.0
            },
            {
              "time_epoch": 1671534000,
              "time": "2022-12-20 11:00",
              "temp_c": 10.7,
              "temp_f": 51.3,
              "is_day": 1,
              "condition": {
                "text": "Patchy rain possible",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
                "code": 1063
              },
              "wind_mph": 8.7,
              "wind_kph": 14.0,
              "wind_degree": 247,
              "wind_dir": "WSW",
              "pressure_mb": 1008.0,
              "pressure_in": 29.77,
              "precip_mm": 0.1,
              "precip_in": 0.0,
              "humidity": 76,
              "cloud": 77,
              "feelslike_c": 8.9,
              "feelslike_f": 48.0,
              "windchill_c": 8.9,
              "windchill_f": 48.0,
              "heatindex_c": 10.7,
              "heatindex_f": 51.3,
              "dewpoint_c": 6.7,
              "dewpoint_f": 44.1,
              "will_it_rain": 1,
              "chance_of_rain": 79,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10.0,
              "vis_miles": 6.0,
              "gust_mph": 10.7,
              "gust_kph": 17.3,
              "uv": 3.0
            },
            {
              "time_epoch": 1671537600,
              "time": "2022-12-20 12:00",
              "temp_c": 11.2,
              "temp_f": 52.2,
              "is_day": 1,
              "condition": {
                "text": "Sunny",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                "code": 1000
              },
              "wind_mph": 8.9,
              "wind_kph": 14.4,
              "wind_degree": 246,
              "wind_dir": "WSW",
              "pressure_mb": 1008.0,
              "pressure_in": 29.78,
              "precip_mm": 0.0,
              "precip_in": 0.0,
              "humidity": 72,
              "cloud": 2,
              "feelslike_c": 9.5,
              "feelslike_f": 49.1,
              "windchill_c": 9.5,
              "windchill_f": 49.1,
              "heatindex_c": 11.2,
              "heatindex_f": 52.2,
              "dewpoint_c": 6.4,
              "dewpoint_f": 43.5,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10.0,
              "vis_miles": 6.0,
              "gust_mph": 10.3,
              "gust_kph": 16.6,
              "uv": 4.0
            },
            {
              "time_epoch": 1671541200,
              "time": "2022-12-20 13:00",
              "temp_c": 12.0,
              "temp_f": 53.6,
              "is_day": 1,
              "condition": {
                "text": "Sunny",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                "code": 1000
              },
              "wind_mph": 8.1,
              "wind_kph": 13.0,
              "wind_degree": 244,
              "wind_dir": "WSW",
              "pressure_mb": 1008.0,
              "pressure_in": 29.78,
              "precip_mm": 0.0,
              "precip_in": 0.0,
              "humidity": 70,
              "cloud": 2,
              "feelslike_c": 10.6,
              "feelslike_f": 51.1,
              "windchill_c": 10.6,
              "windchill_f": 51.1,
              "heatindex_c": 12.0,
              "heatindex_f": 53.6,
              "dewpoint_c": 6.6,
              "dewpoint_f": 43.9,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10.0,
              "vis_miles": 6.0,
              "gust_mph": 9.2,
              "gust_kph": 14.8,
              "uv": 4.0
            },
            {
              "time_epoch": 1671544800,
              "time": "2022-12-20 14:00",
              "temp_c": 10.9,
              "temp_f": 51.6,
              "is_day": 1,
              "condition": {
                "text": "Sunny",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                "code": 1000
              },
              "wind_mph": 7.6,
              "wind_kph": 12.2,
              "wind_degree": 240,
              "wind_dir": "WSW",
              "pressure_mb": 1009.0,
              "pressure_in": 29.78,
              "precip_mm": 0.0,
              "precip_in": 0.0,
              "humidity": 71,
              "cloud": 6,
              "feelslike_c": 9.4,
              "feelslike_f": 48.9,
              "windchill_c": 9.4,
              "windchill_f": 48.9,
              "heatindex_c": 10.9,
              "heatindex_f": 51.6,
              "dewpoint_c": 5.9,
              "dewpoint_f": 42.6,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10.0,
              "vis_miles": 6.0,
              "gust_mph": 8.7,
              "gust_kph": 14.0,
              "uv": 4.0
            },
            {
              "time_epoch": 1671548400,
              "time": "2022-12-20 15:00",
              "temp_c": 10.2,
              "temp_f": 50.4,
              "is_day": 1,
              "condition": {
                "text": "Sunny",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                "code": 1000
              },
              "wind_mph": 7.2,
              "wind_kph": 11.5,
              "wind_degree": 239,
              "wind_dir": "WSW",
              "pressure_mb": 1009.0,
              "pressure_in": 29.78,
              "precip_mm": 0.0,
              "precip_in": 0.0,
              "humidity": 75,
              "cloud": 11,
              "feelslike_c": 8.6,
              "feelslike_f": 47.5,
              "windchill_c": 8.6,
              "windchill_f": 47.5,
              "heatindex_c": 10.2,
              "heatindex_f": 50.4,
              "dewpoint_c": 5.9,
              "dewpoint_f": 42.6,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10.0,
              "vis_miles": 6.0,
              "gust_mph": 8.9,
              "gust_kph": 14.4,
              "uv": 4.0
            },
            {
              "time_epoch": 1671552000,
              "time": "2022-12-20 16:00",
              "temp_c": 9.6,
              "temp_f": 49.3,
              "is_day": 0,
              "condition": {
                "text": "Clear",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                "code": 1000
              },
              "wind_mph": 5.4,
              "wind_kph": 8.6,
              "wind_degree": 227,
              "wind_dir": "SW",
              "pressure_mb": 1009.0,
              "pressure_in": 29.79,
              "precip_mm": 0.0,
              "precip_in": 0.0,
              "humidity": 79,
              "cloud": 10,
              "feelslike_c": 8.4,
              "feelslike_f": 47.1,
              "windchill_c": 8.4,
              "windchill_f": 47.1,
              "heatindex_c": 9.6,
              "heatindex_f": 49.3,
              "dewpoint_c": 6.2,
              "dewpoint_f": 43.2,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10.0,
              "vis_miles": 6.0,
              "gust_mph": 6.9,
              "gust_kph": 11.2,
              "uv": 1.0
            },
            {
              "time_epoch": 1671555600,
              "time": "2022-12-20 17:00",
              "temp_c": 9.4,
              "temp_f": 48.9,
              "is_day": 0,
              "condition": {
                "text": "Clear",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                "code": 1000
              },
              "wind_mph": 4.9,
              "wind_kph": 7.9,
              "wind_degree": 220,
              "wind_dir": "SW",
              "pressure_mb": 1009.0,
              "pressure_in": 29.8,
              "precip_mm": 0.0,
              "precip_in": 0.0,
              "humidity": 83,
              "cloud": 9,
              "feelslike_c": 8.3,
              "feelslike_f": 46.9,
              "windchill_c": 8.3,
              "windchill_f": 46.9,
              "heatindex_c": 9.4,
              "heatindex_f": 48.9,
              "dewpoint_c": 6.6,
              "dewpoint_f": 43.9,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10.0,
              "vis_miles": 6.0,
              "gust_mph": 6.3,
              "gust_kph": 10.1,
              "uv": 1.0
            },
            {
              "time_epoch": 1671559200,
              "time": "2022-12-20 18:00",
              "temp_c": 8.9,
              "temp_f": 48.0,
              "is_day": 0,
              "condition": {
                "text": "Clear",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                "code": 1000
              },
              "wind_mph": 4.7,
              "wind_kph": 7.6,
              "wind_degree": 212,
              "wind_dir": "SSW",
              "pressure_mb": 1010.0,
              "pressure_in": 29.81,
              "precip_mm": 0.0,
              "precip_in": 0.0,
              "humidity": 84,
              "cloud": 16,
              "feelslike_c": 7.8,
              "feelslike_f": 46.0,
              "windchill_c": 7.8,
              "windchill_f": 46.0,
              "heatindex_c": 8.9,
              "heatindex_f": 48.0,
              "dewpoint_c": 6.4,
              "dewpoint_f": 43.5,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10.0,
              "vis_miles": 6.0,
              "gust_mph": 6.3,
              "gust_kph": 10.1,
              "uv": 1.0
            },
            {
              "time_epoch": 1671562800,
              "time": "2022-12-20 19:00",
              "temp_c": 8.4,
              "temp_f": 47.1,
              "is_day": 0,
              "condition": {
                "text": "Partly cloudy",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
                "code": 1003
              },
              "wind_mph": 4.0,
              "wind_kph": 6.5,
              "wind_degree": 206,
              "wind_dir": "SSW",
              "pressure_mb": 1010.0,
              "pressure_in": 29.82,
              "precip_mm": 0.0,
              "precip_in": 0.0,
              "humidity": 86,
              "cloud": 33,
              "feelslike_c": 7.5,
              "feelslike_f": 45.5,
              "windchill_c": 7.5,
              "windchill_f": 45.5,
              "heatindex_c": 8.4,
              "heatindex_f": 47.1,
              "dewpoint_c": 6.1,
              "dewpoint_f": 43.0,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10.0,
              "vis_miles": 6.0,
              "gust_mph": 5.8,
              "gust_kph": 9.4,
              "uv": 1.0
            },
            {
              "time_epoch": 1671566400,
              "time": "2022-12-20 20:00",
              "temp_c": 7.5,
              "temp_f": 45.5,
              "is_day": 0,
              "condition": {
                "text": "Partly cloudy",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
                "code": 1003
              },
              "wind_mph": 4.0,
              "wind_kph": 6.5,
              "wind_degree": 200,
              "wind_dir": "SSW",
              "pressure_mb": 1010.0,
              "pressure_in": 29.82,
              "precip_mm": 0.0,
              "precip_in": 0.0,
              "humidity": 86,
              "cloud": 33,
              "feelslike_c": 6.5,
              "feelslike_f": 43.7,
              "windchill_c": 6.5,
              "windchill_f": 43.7,
              "heatindex_c": 7.5,
              "heatindex_f": 45.5,
              "dewpoint_c": 5.2,
              "dewpoint_f": 41.4,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10.0,
              "vis_miles": 6.0,
              "gust_mph": 6.7,
              "gust_kph": 10.8,
              "uv": 1.0
            },
            {
              "time_epoch": 1671570000,
              "time": "2022-12-20 21:00",
              "temp_c": 7.3,
              "temp_f": 45.1,
              "is_day": 0,
              "condition": {
                "text": "Partly cloudy",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
                "code": 1003
              },
              "wind_mph": 4.3,
              "wind_kph": 6.8,
              "wind_degree": 197,
              "wind_dir": "SSW",
              "pressure_mb": 1010.0,
              "pressure_in": 29.82,
              "precip_mm": 0.0,
              "precip_in": 0.0,
              "humidity": 86,
              "cloud": 46,
              "feelslike_c": 6.1,
              "feelslike_f": 43.0,
              "windchill_c": 6.1,
              "windchill_f": 43.0,
              "heatindex_c": 7.3,
              "heatindex_f": 45.1,
              "dewpoint_c": 5.1,
              "dewpoint_f": 41.2,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10.0,
              "vis_miles": 6.0,
              "gust_mph": 7.2,
              "gust_kph": 11.5,
              "uv": 1.0
            },
            {
              "time_epoch": 1671573600,
              "time": "2022-12-20 22:00",
              "temp_c": 6.8,
              "temp_f": 44.2,
              "is_day": 0,
              "condition": {
                "text": "Partly cloudy",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
                "code": 1003
              },
              "wind_mph": 4.5,
              "wind_kph": 7.2,
              "wind_degree": 197,
              "wind_dir": "SSW",
              "pressure_mb": 1010.0,
              "pressure_in": 29.81,
              "precip_mm": 0.0,
              "precip_in": 0.0,
              "humidity": 87,
              "cloud": 28,
              "feelslike_c": 5.5,
              "feelslike_f": 41.9,
              "windchill_c": 5.5,
              "windchill_f": 41.9,
              "heatindex_c": 6.8,
              "heatindex_f": 44.2,
              "dewpoint_c": 4.8,
              "dewpoint_f": 40.6,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10.0,
              "vis_miles": 6.0,
              "gust_mph": 7.8,
              "gust_kph": 12.6,
              "uv": 1.0
            },
            {
              "time_epoch": 1671577200,
              "time": "2022-12-20 23:00",
              "temp_c": 6.5,
              "temp_f": 43.7,
              "is_day": 0,
              "condition": {
                "text": "Clear",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                "code": 1000
              },
              "wind_mph": 4.7,
              "wind_kph": 7.6,
              "wind_degree": 196,
              "wind_dir": "SSW",
              "pressure_mb": 1009.0,
              "pressure_in": 29.8,
              "precip_mm": 0.0,
              "precip_in": 0.0,
              "humidity": 88,
              "cloud": 14,
              "feelslike_c": 5.0,
              "feelslike_f": 41.0,
              "windchill_c": 5.0,
              "windchill_f": 41.0,
              "heatindex_c": 6.5,
              "heatindex_f": 43.7,
              "dewpoint_c": 4.6,
              "dewpoint_f": 40.3,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10.0,
              "vis_miles": 6.0,
              "gust_mph": 8.5,
              "gust_kph": 13.7,
              "uv": 1.0
            }
          ]
        },
        {
          "date": "2022-12-21",
          "date_epoch": 1671580800,
          "day": {
            "maxtemp_c": 9.1,
            "maxtemp_f": 48.4,
            "mintemp_c": 6.0,
            "mintemp_f": 42.8,
            "avgtemp_c": 7.8,
            "avgtemp_f": 46.1,
            "maxwind_mph": 12.3,
            "maxwind_kph": 19.8,
            "totalprecip_mm": 2.2,
            "totalprecip_in": 0.09,
            "totalsnow_cm": 0.0,
            "avgvis_km": 9.9,
            "avgvis_miles": 6.0,
            "avghumidity": 78.0,
            "daily_will_it_rain": 1,
            "daily_chance_of_rain": 78,
            "daily_will_it_snow": 0,
            "daily_chance_of_snow": 0,
            "condition": {
              "text": "Patchy rain possible",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
              "code": 1063
            },
            "uv": 2.0
          },
          "astro": {
            "sunrise": "08:04 AM",
            "sunset": "03:53 PM",
            "moonrise": "05:47 AM",
            "moonset": "01:58 PM",
            "moon_phase": "Waning Crescent",
            "moon_illumination": "4"
          },
          "hour": [
            {
              "time_epoch": 1671580800,
              "time": "2022-12-21 00:00",
              "temp_c": 6.0,
              "temp_f": 42.8,
              "is_day": 0,
              "condition": {
                "text": "Clear",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                "code": 1000
              },
              "wind_mph": 4.7,
              "wind_kph": 7.6,
              "wind_degree": 191,
              "wind_dir": "SSW",
              "pressure_mb": 1009.0,
              "pressure_in": 29.8,
              "precip_mm": 0.0,
              "precip_in": 0.0,
              "humidity": 88,
              "cloud": 15,
              "feelslike_c": 4.4,
              "feelslike_f": 39.9,
              "windchill_c": 4.4,
              "windchill_f": 39.9,
              "heatindex_c": 6.0,
              "heatindex_f": 42.8,
              "dewpoint_c": 4.1,
              "dewpoint_f": 39.4,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10.0,
              "vis_miles": 6.0,
              "gust_mph": 9.2,
              "gust_kph": 14.8,
              "uv": 1.0
            },
            {
              "time_epoch": 1671584400,
              "time": "2022-12-21 01:00",
              "temp_c": 6.2,
              "temp_f": 43.2,
              "is_day": 0,
              "condition": {
                "text": "Partly cloudy",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
                "code": 1003
              },
              "wind_mph": 5.4,
              "wind_kph": 8.6,
              "wind_degree": 180,
              "wind_dir": "S",
              "pressure_mb": 1008.0,
              "pressure_in": 29.78,
              "precip_mm": 0.0,
              "precip_in": 0.0,
              "humidity": 86,
              "cloud": 34,
              "feelslike_c": 4.4,
              "feelslike_f": 39.9,
              "windchill_c": 4.4,
              "windchill_f": 39.9,
              "heatindex_c": 6.2,
              "heatindex_f": 43.2,
              "dewpoint_c": 4.1,
              "dewpoint_f": 39.4,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10.0,
              "vis_miles": 6.0,
              "gust_mph": 10.5,
              "gust_kph": 16.9,
              "uv": 1.0
            },
            {
              "time_epoch": 1671588000,
              "time": "2022-12-21 02:00",
              "temp_c": 6.5,
              "temp_f": 43.7,
              "is_day": 0,
              "condition": {
                "text": "Cloudy",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/119.png",
                "code": 1006
              },
              "wind_mph": 6.9,
              "wind_kph": 11.2,
              "wind_degree": 191,
              "wind_dir": "SSW",
              "pressure_mb": 1008.0,
              "pressure_in": 29.77,
              "precip_mm": 0.0,
              "precip_in": 0.0,
              "humidity": 85,
              "cloud": 71,
              "feelslike_c": 4.2,
              "feelslike_f": 39.6,
              "windchill_c": 4.2,
              "windchill_f": 39.6,
              "heatindex_c": 6.5,
              "heatindex_f": 43.7,
              "dewpoint_c": 4.2,
              "dewpoint_f": 39.6,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10.0,
              "vis_miles": 6.0,
              "gust_mph": 13.0,
              "gust_kph": 20.9,
              "uv": 1.0
            },
            {
              "time_epoch": 1671591600,
              "time": "2022-12-21 03:00",
              "temp_c": 7.1,
              "temp_f": 44.8,
              "is_day": 0,
              "condition": {
                "text": "Cloudy",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/119.png",
                "code": 1006
              },
              "wind_mph": 8.1,
              "wind_kph": 13.0,
              "wind_degree": 198,
              "wind_dir": "SSW",
              "pressure_mb": 1008.0,
              "pressure_in": 29.75,
              "precip_mm": 0.0,
              "precip_in": 0.0,
              "humidity": 85,
              "cloud": 87,
              "feelslike_c": 4.6,
              "feelslike_f": 40.3,
              "windchill_c": 4.6,
              "windchill_f": 40.3,
              "heatindex_c": 7.1,
              "heatindex_f": 44.8,
              "dewpoint_c": 4.8,
              "dewpoint_f": 40.6,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10.0,
              "vis_miles": 6.0,
              "gust_mph": 14.5,
              "gust_kph": 23.4,
              "uv": 1.0
            },
            {
              "time_epoch": 1671595200,
              "time": "2022-12-21 04:00",
              "temp_c": 8.0,
              "temp_f": 46.4,
              "is_day": 0,
              "condition": {
                "text": "Cloudy",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/119.png",
                "code": 1006
              },
              "wind_mph": 9.2,
              "wind_kph": 14.8,
              "wind_degree": 208,
              "wind_dir": "SSW",
              "pressure_mb": 1007.0,
              "pressure_in": 29.74,
              "precip_mm": 0.0,
              "precip_in": 0.0,
              "humidity": 81,
              "cloud": 63,
              "feelslike_c": 5.5,
              "feelslike_f": 41.9,
              "windchill_c": 5.5,
              "windchill_f": 41.9,
              "heatindex_c": 8.0,
              "heatindex_f": 46.4,
              "dewpoint_c": 5.0,
              "dewpoint_f": 41.0,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10.0,
              "vis_miles": 6.0,
              "gust_mph": 15.4,
              "gust_kph": 24.8,
              "uv": 1.0
            },
            {
              "time_epoch": 1671598800,
              "time": "2022-12-21 05:00",
              "temp_c": 8.4,
              "temp_f": 47.1,
              "is_day": 0,
              "condition": {
                "text": "Partly cloudy",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
                "code": 1003
              },
              "wind_mph": 11.0,
              "wind_kph": 17.6,
              "wind_degree": 211,
              "wind_dir": "SSW",
              "pressure_mb": 1006.0,
              "pressure_in": 29.72,
              "precip_mm": 0.0,
              "precip_in": 0.0,
              "humidity": 75,
              "cloud": 47,
              "feelslike_c": 5.6,
              "feelslike_f": 42.1,
              "windchill_c": 5.6,
              "windchill_f": 42.1,
              "heatindex_c": 8.4,
              "heatindex_f": 47.1,
              "dewpoint_c": 4.2,
              "dewpoint_f": 39.6,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10.0,
              "vis_miles": 6.0,
              "gust_mph": 18.6,
              "gust_kph": 29.9,
              "uv": 1.0
            },
            {
              "time_epoch": 1671602400,
              "time": "2022-12-21 06:00",
              "temp_c": 8.4,
              "temp_f": 47.1,
              "is_day": 0,
              "condition": {
                "text": "Overcast",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/122.png",
                "code": 1009
              },
              "wind_mph": 11.6,
              "wind_kph": 18.7,
              "wind_degree": 216,
              "wind_dir": "SW",
              "pressure_mb": 1006.0,
              "pressure_in": 29.71,
              "precip_mm": 0.0,
              "precip_in": 0.0,
              "humidity": 76,
              "cloud": 90,
              "feelslike_c": 5.5,
              "feelslike_f": 41.9,
              "windchill_c": 5.5,
              "windchill_f": 41.9,
              "heatindex_c": 8.4,
              "heatindex_f": 47.1,
              "dewpoint_c": 4.4,
              "dewpoint_f": 39.9,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10.0,
              "vis_miles": 6.0,
              "gust_mph": 19.7,
              "gust_kph": 31.7,
              "uv": 1.0
            },
            {
              "time_epoch": 1671606000,
              "time": "2022-12-21 07:00",
              "temp_c": 8.1,
              "temp_f": 46.6,
              "is_day": 0,
              "condition": {
                "text": "Thundery outbreaks possible",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/200.png",
                "code": 1087
              },
              "wind_mph": 11.9,
              "wind_kph": 19.1,
              "wind_degree": 220,
              "wind_dir": "SW",
              "pressure_mb": 1006.0,
              "pressure_in": 29.72,
              "precip_mm": 0.0,
              "precip_in": 0.0,
              "humidity": 81,
              "cloud": 100,
              "feelslike_c": 5.1,
              "feelslike_f": 41.2,
              "windchill_c": 5.1,
              "windchill_f": 41.2,
              "heatindex_c": 8.1,
              "heatindex_f": 46.6,
              "dewpoint_c": 5.1,
              "dewpoint_f": 41.2,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 9.0,
              "vis_miles": 5.0,
              "gust_mph": 19.5,
              "gust_kph": 31.3,
              "uv": 1.0
            },
            {
              "time_epoch": 1671609600,
              "time": "2022-12-21 08:00",
              "temp_c": 8.1,
              "temp_f": 46.6,
              "is_day": 0,
              "condition": {
                "text": "Overcast",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/122.png",
                "code": 1009
              },
              "wind_mph": 11.2,
              "wind_kph": 18.0,
              "wind_degree": 241,
              "wind_dir": "WSW",
              "pressure_mb": 1006.0,
              "pressure_in": 29.72,
              "precip_mm": 0.0,
              "precip_in": 0.0,
              "humidity": 89,
              "cloud": 100,
              "feelslike_c": 5.2,
              "feelslike_f": 41.4,
              "windchill_c": 5.2,
              "windchill_f": 41.4,
              "heatindex_c": 8.1,
              "heatindex_f": 46.6,
              "dewpoint_c": 6.4,
              "dewpoint_f": 43.5,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10.0,
              "vis_miles": 6.0,
              "gust_mph": 17.0,
              "gust_kph": 27.4,
              "uv": 1.0
            },
            {
              "time_epoch": 1671613200,
              "time": "2022-12-21 09:00",
              "temp_c": 7.7,
              "temp_f": 45.9,
              "is_day": 1,
              "condition": {
                "text": "Patchy light rain",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/293.png",
                "code": 1180
              },
              "wind_mph": 9.2,
              "wind_kph": 14.8,
              "wind_degree": 266,
              "wind_dir": "W",
              "pressure_mb": 1008.0,
              "pressure_in": 29.75,
              "precip_mm": 1.8,
              "precip_in": 0.07,
              "humidity": 86,
              "cloud": 69,
              "feelslike_c": 5.1,
              "feelslike_f": 41.2,
              "windchill_c": 5.1,
              "windchill_f": 41.2,
              "heatindex_c": 7.7,
              "heatindex_f": 45.9,
              "dewpoint_c": 5.4,
              "dewpoint_f": 41.7,
              "will_it_rain": 0,
              "chance_of_rain": 60,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 9.0,
              "vis_miles": 5.0,
              "gust_mph": 13.6,
              "gust_kph": 22.0,
              "uv": 2.0
            },
            {
              "time_epoch": 1671616800,
              "time": "2022-12-21 10:00",
              "temp_c": 8.0,
              "temp_f": 46.4,
              "is_day": 1,
              "condition": {
                "text": "Sunny",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                "code": 1000
              },
              "wind_mph": 9.6,
              "wind_kph": 15.5,
              "wind_degree": 232,
              "wind_dir": "SW",
              "pressure_mb": 1008.0,
              "pressure_in": 29.75,
              "precip_mm": 0.0,
              "precip_in": 0.0,
              "humidity": 75,
              "cloud": 24,
              "feelslike_c": 5.4,
              "feelslike_f": 41.7,
              "windchill_c": 5.4,
              "windchill_f": 41.7,
              "heatindex_c": 8.0,
              "heatindex_f": 46.4,
              "dewpoint_c": 3.8,
              "dewpoint_f": 38.8,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10.0,
              "vis_miles": 6.0,
              "gust_mph": 14.5,
              "gust_kph": 23.4,
              "uv": 3.0
            },
            {
              "time_epoch": 1671620400,
              "time": "2022-12-21 11:00",
              "temp_c": 8.6,
              "temp_f": 47.5,
              "is_day": 1,
              "condition": {
                "text": "Patchy rain possible",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
                "code": 1063
              },
              "wind_mph": 10.7,
              "wind_kph": 17.3,
              "wind_degree": 240,
              "wind_dir": "WSW",
              "pressure_mb": 1008.0,
              "pressure_in": 29.77,
              "precip_mm": 0.4,
              "precip_in": 0.02,
              "humidity": 70,
              "cloud": 83,
              "feelslike_c": 5.9,
              "feelslike_f": 42.6,
              "windchill_c": 5.9,
              "windchill_f": 42.6,
              "heatindex_c": 8.6,
              "heatindex_f": 47.5,
              "dewpoint_c": 3.5,
              "dewpoint_f": 38.3,
              "will_it_rain": 1,
              "chance_of_rain": 78,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 9.0,
              "vis_miles": 5.0,
              "gust_mph": 15.0,
              "gust_kph": 24.1,
              "uv": 2.0
            },
            {
              "time_epoch": 1671624000,
              "time": "2022-12-21 12:00",
              "temp_c": 8.9,
              "temp_f": 48.0,
              "is_day": 1,
              "condition": {
                "text": "Sunny",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                "code": 1000
              },
              "wind_mph": 12.1,
              "wind_kph": 19.4,
              "wind_degree": 242,
              "wind_dir": "WSW",
              "pressure_mb": 1008.0,
              "pressure_in": 29.76,
              "precip_mm": 0.0,
              "precip_in": 0.0,
              "humidity": 68,
              "cloud": 9,
              "feelslike_c": 6.0,
              "feelslike_f": 42.8,
              "windchill_c": 6.0,
              "windchill_f": 42.8,
              "heatindex_c": 8.9,
              "heatindex_f": 48.0,
              "dewpoint_c": 3.4,
              "dewpoint_f": 38.1,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10.0,
              "vis_miles": 6.0,
              "gust_mph": 16.8,
              "gust_kph": 27.0,
              "uv": 3.0
            },
            {
              "time_epoch": 1671627600,
              "time": "2022-12-21 13:00",
              "temp_c": 9.1,
              "temp_f": 48.4,
              "is_day": 1,
              "condition": {
                "text": "Sunny",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                "code": 1000
              },
              "wind_mph": 12.1,
              "wind_kph": 19.4,
              "wind_degree": 244,
              "wind_dir": "WSW",
              "pressure_mb": 1008.0,
              "pressure_in": 29.75,
              "precip_mm": 0.0,
              "precip_in": 0.0,
              "humidity": 66,
              "cloud": 3,
              "feelslike_c": 6.3,
              "feelslike_f": 43.3,
              "windchill_c": 6.3,
              "windchill_f": 43.3,
              "heatindex_c": 9.1,
              "heatindex_f": 48.4,
              "dewpoint_c": 3.1,
              "dewpoint_f": 37.6,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10.0,
              "vis_miles": 6.0,
              "gust_mph": 16.3,
              "gust_kph": 26.3,
              "uv": 3.0
            },
            {
              "time_epoch": 1671631200,
              "time": "2022-12-21 14:00",
              "temp_c": 8.9,
              "temp_f": 48.0,
              "is_day": 1,
              "condition": {
                "text": "Sunny",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                "code": 1000
              },
              "wind_mph": 12.3,
              "wind_kph": 19.8,
              "wind_degree": 240,
              "wind_dir": "WSW",
              "pressure_mb": 1008.0,
              "pressure_in": 29.75,
              "precip_mm": 0.0,
              "precip_in": 0.0,
              "humidity": 68,
              "cloud": 4,
              "feelslike_c": 6.0,
              "feelslike_f": 42.8,
              "windchill_c": 6.0,
              "windchill_f": 42.8,
              "heatindex_c": 8.9,
              "heatindex_f": 48.0,
              "dewpoint_c": 3.4,
              "dewpoint_f": 38.1,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10.0,
              "vis_miles": 6.0,
              "gust_mph": 17.4,
              "gust_kph": 28.1,
              "uv": 3.0
            },
            {
              "time_epoch": 1671634800,
              "time": "2022-12-21 15:00",
              "temp_c": 8.6,
              "temp_f": 47.5,
              "is_day": 1,
              "condition": {
                "text": "Sunny",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                "code": 1000
              },
              "wind_mph": 11.6,
              "wind_kph": 18.7,
              "wind_degree": 245,
              "wind_dir": "WSW",
              "pressure_mb": 1008.0,
              "pressure_in": 29.77,
              "precip_mm": 0.0,
              "precip_in": 0.0,
              "humidity": 70,
              "cloud": 9,
              "feelslike_c": 5.7,
              "feelslike_f": 42.3,
              "windchill_c": 5.7,
              "windchill_f": 42.3,
              "heatindex_c": 8.6,
              "heatindex_f": 47.5,
              "dewpoint_c": 3.5,
              "dewpoint_f": 38.3,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10.0,
              "vis_miles": 6.0,
              "gust_mph": 16.8,
              "gust_kph": 27.0,
              "uv": 3.0
            },
            {
              "time_epoch": 1671638400,
              "time": "2022-12-21 16:00",
              "temp_c": 7.9,
              "temp_f": 46.2,
              "is_day": 0,
              "condition": {
                "text": "Partly cloudy",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
                "code": 1003
              },
              "wind_mph": 11.4,
              "wind_kph": 18.4,
              "wind_degree": 243,
              "wind_dir": "WSW",
              "pressure_mb": 1008.0,
              "pressure_in": 29.78,
              "precip_mm": 0.0,
              "precip_in": 0.0,
              "humidity": 73,
              "cloud": 25,
              "feelslike_c": 4.9,
              "feelslike_f": 40.8,
              "windchill_c": 4.9,
              "windchill_f": 40.8,
              "heatindex_c": 7.9,
              "heatindex_f": 46.2,
              "dewpoint_c": 3.3,
              "dewpoint_f": 37.9,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10.0,
              "vis_miles": 6.0,
              "gust_mph": 17.4,
              "gust_kph": 28.1,
              "uv": 1.0
            },
            {
              "time_epoch": 1671642000,
              "time": "2022-12-21 17:00",
              "temp_c": 7.8,
              "temp_f": 46.0,
              "is_day": 0,
              "condition": {
                "text": "Clear",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                "code": 1000
              },
              "wind_mph": 11.0,
              "wind_kph": 17.6,
              "wind_degree": 239,
              "wind_dir": "WSW",
              "pressure_mb": 1009.0,
              "pressure_in": 29.78,
              "precip_mm": 0.0,
              "precip_in": 0.0,
              "humidity": 74,
              "cloud": 8,
              "feelslike_c": 4.9,
              "feelslike_f": 40.8,
              "windchill_c": 4.9,
              "windchill_f": 40.8,
              "heatindex_c": 7.8,
              "heatindex_f": 46.0,
              "dewpoint_c": 3.5,
              "dewpoint_f": 38.3,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10.0,
              "vis_miles": 6.0,
              "gust_mph": 16.3,
              "gust_kph": 26.3,
              "uv": 1.0
            },
            {
              "time_epoch": 1671645600,
              "time": "2022-12-21 18:00",
              "temp_c": 7.5,
              "temp_f": 45.5,
              "is_day": 0,
              "condition": {
                "text": "Clear",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                "code": 1000
              },
              "wind_mph": 10.5,
              "wind_kph": 16.9,
              "wind_degree": 234,
              "wind_dir": "SW",
              "pressure_mb": 1009.0,
              "pressure_in": 29.78,
              "precip_mm": 0.0,
              "precip_in": 0.0,
              "humidity": 77,
              "cloud": 18,
              "feelslike_c": 4.6,
              "feelslike_f": 40.3,
              "windchill_c": 4.6,
              "windchill_f": 40.3,
              "heatindex_c": 7.5,
              "heatindex_f": 45.5,
              "dewpoint_c": 3.7,
              "dewpoint_f": 38.7,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10.0,
              "vis_miles": 6.0,
              "gust_mph": 15.9,
              "gust_kph": 25.6,
              "uv": 1.0
            },
            {
              "time_epoch": 1671649200,
              "time": "2022-12-21 19:00",
              "temp_c": 7.3,
              "temp_f": 45.1,
              "is_day": 0,
              "condition": {
                "text": "Cloudy",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/119.png",
                "code": 1006
              },
              "wind_mph": 10.1,
              "wind_kph": 16.2,
              "wind_degree": 229,
              "wind_dir": "SW",
              "pressure_mb": 1009.0,
              "pressure_in": 29.79,
              "precip_mm": 0.0,
              "precip_in": 0.0,
              "humidity": 80,
              "cloud": 65,
              "feelslike_c": 4.4,
              "feelslike_f": 39.9,
              "windchill_c": 4.4,
              "windchill_f": 39.9,
              "heatindex_c": 7.3,
              "heatindex_f": 45.1,
              "dewpoint_c": 4.1,
              "dewpoint_f": 39.4,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10.0,
              "vis_miles": 6.0,
              "gust_mph": 15.9,
              "gust_kph": 25.6,
              "uv": 1.0
            },
            {
              "time_epoch": 1671652800,
              "time": "2022-12-21 20:00",
              "temp_c": 7.4,
              "temp_f": 45.3,
              "is_day": 0,
              "condition": {
                "text": "Overcast",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/122.png",
                "code": 1009
              },
              "wind_mph": 10.1,
              "wind_kph": 16.2,
              "wind_degree": 228,
              "wind_dir": "SW",
              "pressure_mb": 1009.0,
              "pressure_in": 29.79,
              "precip_mm": 0.0,
              "precip_in": 0.0,
              "humidity": 80,
              "cloud": 100,
              "feelslike_c": 4.5,
              "feelslike_f": 40.1,
              "windchill_c": 4.5,
              "windchill_f": 40.1,
              "heatindex_c": 7.4,
              "heatindex_f": 45.3,
              "dewpoint_c": 4.1,
              "dewpoint_f": 39.4,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10.0,
              "vis_miles": 6.0,
              "gust_mph": 16.1,
              "gust_kph": 25.9,
              "uv": 1.0
            },
            {
              "time_epoch": 1671656400,
              "time": "2022-12-21 21:00",
              "temp_c": 7.7,
              "temp_f": 45.9,
              "is_day": 0,
              "condition": {
                "text": "Partly cloudy",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
                "code": 1003
              },
              "wind_mph": 9.6,
              "wind_kph": 15.5,
              "wind_degree": 226,
              "wind_dir": "SW",
              "pressure_mb": 1009.0,
              "pressure_in": 29.79,
              "precip_mm": 0.0,
              "precip_in": 0.0,
              "humidity": 78,
              "cloud": 43,
              "feelslike_c": 5.0,
              "feelslike_f": 41.0,
              "windchill_c": 5.0,
              "windchill_f": 41.0,
              "heatindex_c": 7.7,
              "heatindex_f": 45.9,
              "dewpoint_c": 4.1,
              "dewpoint_f": 39.4,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10.0,
              "vis_miles": 6.0,
              "gust_mph": 15.2,
              "gust_kph": 24.5,
              "uv": 1.0
            },
            {
              "time_epoch": 1671660000,
              "time": "2022-12-21 22:00",
              "temp_c": 7.9,
              "temp_f": 46.2,
              "is_day": 0,
              "condition": {
                "text": "Cloudy",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/119.png",
                "code": 1006
              },
              "wind_mph": 8.7,
              "wind_kph": 14.0,
              "wind_degree": 218,
              "wind_dir": "SW",
              "pressure_mb": 1008.0,
              "pressure_in": 29.77,
              "precip_mm": 0.0,
              "precip_in": 0.0,
              "humidity": 77,
              "cloud": 65,
              "feelslike_c": 5.5,
              "feelslike_f": 41.9,
              "windchill_c": 5.5,
              "windchill_f": 41.9,
              "heatindex_c": 7.9,
              "heatindex_f": 46.2,
              "dewpoint_c": 4.2,
              "dewpoint_f": 39.6,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10.0,
              "vis_miles": 6.0,
              "gust_mph": 14.1,
              "gust_kph": 22.7,
              "uv": 1.0
            },
            {
              "time_epoch": 1671663600,
              "time": "2022-12-21 23:00",
              "temp_c": 8.0,
              "temp_f": 46.4,
              "is_day": 0,
              "condition": {
                "text": "Overcast",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/122.png",
                "code": 1009
              },
              "wind_mph": 8.1,
              "wind_kph": 13.0,
              "wind_degree": 205,
              "wind_dir": "SSW",
              "pressure_mb": 1007.0,
              "pressure_in": 29.74,
              "precip_mm": 0.0,
              "precip_in": 0.0,
              "humidity": 84,
              "cloud": 100,
              "feelslike_c": 5.7,
              "feelslike_f": 42.3,
              "windchill_c": 5.7,
              "windchill_f": 42.3,
              "heatindex_c": 8.0,
              "heatindex_f": 46.4,
              "dewpoint_c": 5.5,
              "dewpoint_f": 41.9,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10.0,
              "vis_miles": 6.0,
              "gust_mph": 12.8,
              "gust_kph": 20.5,
              "uv": 1.0
            }
          ]
        }
      ]
    },
    "alerts": {
      "alert": [
        {
          "headline":
              "Flood Warning issued January 05 at 9:47PM EST until January 07 at 6:15AM EST by NWS",
          "msgtype": "Alert",
          "severity": "Moderate",
          "urgency": "Expected",
          "areas": "Calhoun; Lexington; Richland",
          "category": "Met",
          "certainty": "Likely",
          "event": "Flood Warning",
          "note":
              "Alert for Calhoun; Lexington; Richland (South Carolina) Issued by the National Weather Service",
          "effective": "2021-01-05T21:47:00-05:00",
          "expires": "2021-01-07T06:15:00-05:00",
          "desc":
              "...The Flood Warning continues for the following rivers in South\nCarolina...\nCongaree River At Carolina Eastman affecting Richland, Calhoun\nand Lexington Counties.\nCongaree River At Congaree National Park-Gadsden affecting\nCalhoun and Richland Counties.\nNorth Fork Edisto River At Orangeburg affecting Orangeburg County.\n...The Flood Warning is now in effect until Thursday morning...\nThe Flood Warning continues for\nthe Congaree River At Carolina Eastman.\n* Until Thursday morning.\n* At 9:28 PM EST Tuesday the stage was 115.6 feet.\n* Flood stage is 115.0 feet.\n* Minor flooding is occurring and minor flooding is forecast.\n* Recent Activity...The maximum river stage in the 24 hours ending\nat 9:28 PM EST Tuesday was 118.2 feet.\n* Forecast...The river will rise to 115.7 feet just after midnight\ntonight. It will then fall below flood stage tomorrow morning to\n114.2 feet and begin rising again tomorrow evening. It will rise\nto 114.3 feet early Thursday morning. It will then fall again and\nremain below flood stage.\n* Impact...At 115.0 feet, Flooding occurs in low lying areas of the\nCarolina Eastman Facility and at the Congaree National Park.\n* Flood History...This crest compares to a previous crest of 116.3\nfeet on 12/03/2020.\n&&",
          "instruction":
              "A Flood Warning means that flooding is imminent or occurring. All\ninterested parties should take necessary precautions immediately.\nMotorists should not attempt to drive around barricades or drive\ncars through flooded areas.\nCaution is urged when walking near riverbanks.\nAdditional information is available at www.weather.gov.\nThe next statement will be issued Wednesday morning at 1000 AM EST."
        },
        {
          "headline":
              "Flood Warning issued January 05 at 9:47PM EST until January 09 at 4:00AM EST by NWS",
          "msgtype": "Alert",
          "severity": "Moderate",
          "urgency": "Expected",
          "areas": "Calhoun; Richland",
          "category": "Met",
          "certainty": "Likely",
          "event": "Flood Warning",
          "note":
              "Alert for Calhoun; Richland (South Carolina) Issued by the National Weather Service",
          "effective": "2021-01-05T21:47:00-05:00",
          "expires": "2021-01-09T04:00:00-05:00",
          "desc":
              "...The Flood Warning continues for the following rivers in South\nCarolina...\nCongaree River At Carolina Eastman affecting Richland, Calhoun\nand Lexington Counties.\nCongaree River At Congaree National Park-Gadsden affecting\nCalhoun and Richland Counties.\nNorth Fork Edisto River At Orangeburg affecting Orangeburg County.\n...The Flood Warning is now in effect until early Saturday morning...\nThe Flood Warning continues for\nthe Congaree River At Congaree National Park-Gadsden.\n* Until late Friday night.\n* At 9:00 PM EST Tuesday the stage was 16.5 feet.\n* Flood stage is 15.0 feet.\n* Minor flooding is occurring and minor flooding is forecast.\n* Recent Activity...The maximum river stage in the 24 hours ending\nat 9:00 PM EST Tuesday was 17.2 feet.\n* Forecast...The river is expected to fall below flood stage early\nFriday morning and continue falling to 12.4 feet Sunday evening.\n* Impact...At 15.0 feet, Flooding begins in the Congaree National\nPark. This will begin to produce flooding of portions of the lower\nboardwalk.\n* Impact...At 17.0 feet, The access road to the Sandy Run\nsubdivision becomes flooded. The lower boardwalk in the Congaree\nNational Park becomes flooded by Cedar Creek.\n* Impact...At 18.0 feet, Several homes in the Sandy Run subdivision\nalong the river become flooded. At 18 feet the river covers the\nWeston Lake overlook in the Congaree National Park. Between 18 and\n18.5 feet the river begins to cover sections of the elevated\nboardwalk.\n* Flood History...This crest compares to a previous crest of 16.3\nfeet on 12/03/2020.\n&&",
          "instruction":
              "A Flood Warning means that flooding is imminent or occurring. All\ninterested parties should take necessary precautions immediately.\nMotorists should not attempt to drive around barricades or drive\ncars through flooded areas.\nCaution is urged when walking near riverbanks.\nAdditional information is available at www.weather.gov.\nThe next statement will be issued Wednesday morning at 1000 AM EST."
        }
      ]
    }
  };

  group('Weather model', () {
    final Weather weather = Weather.fromJson(response);

    test('can be intantiated', () {
      expect(Weather, isNotNull);
    });

    test('supports value equality', () {
      expect(Weather, equals(Weather));
    });

    test('serializes json', () {
      expect(weather, isNotNull);
    });

    test('supports value equality in serialized json', () {
      expect(Weather.fromJson(response), equals(weather));
    });

    test('copyWith updates fields', () {
      final newWeather = weather.copyWith(location: weather.location.copyWith(lat: 525.0),);

      expect(newWeather.location.lat, equals(525.0));
      expect(newWeather, isNot(equals(weather)));
    });

    test('deserializes json', () {
      final des = weather.toJson();

      expect(des, equals(response));
    });
  });
}
